# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 971c3bdf59fe8dfacf9cc55f4b2fa9df622a4325ca94a9f728237dd111fdfc523728d72b4ed3285cff786b2ef4321eeec131322c58d3b62c662eb3ef5d31a6be

test:
  secret_key_base: 5864127da85cf97995c770640bce9b646f009c1c229a1c09a2bb02848781bfde820fbd97f455fdf58474563f81c4fe9613032ce3ed0bfa732eace48d7bae442d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
